### ISSUE TITLE
I'm a little confused

### ISSUE THREAD

**Issue by jonathanfishbein1** [jkaye2012/polling-cache#1]
I'm only seeing it run once?

**Comment by jkaye2012** [comment]
Could you show how you're using the cache and what output you're seeing? There are test cases for this behavior and I was able to confirm that the library is working for me locally.

**Comment by jonathanfishbein1** [comment]
`main :: Relude.IO ()
main = do
  let opts = Data.Cache.Polling.basicOptions (Data.Cache.Poling.DelayForMicroseconds 100000) Data.Cache.Polling.Ignore
  cache <-
    Data.Cache.Polling.newPollingCache
      opts
      (Relude.return 1)
  Control.Concurrent.threadDelay 100
  latestResult <- Data.Cache.Polling.Cache.cachedValue cache
  Relude.print latestResult`

**Comment by jonathanfishbein1** [comment]
cabal runs and then exists

Ok I see you have to call cachedValue multiple times to poll

**Comment by jkaye2012** [comment]
So, to be specific, the library will poll regardless of calls to `cachedValue`. The exiting behavior is because there's nothing in that program that tells cabal to keep running (or, rather, not to exit).

You would need to call `cachedValue` multiple times to see values as they change though!

**Comment by jkaye2012** [comment]
I'm going to close this for now since it doesn't appear to be an issue with the library, but please feel free to ask further questions here if you have them.
